cache:
  paths:
    - ./.m2/repository
  # keep cache across branch
  key: "$CI_PROJECT_PATH"

variables:
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -Dmaven.repo.local=./.m2/repository"
  ACCESS_KEY: "$AWS_ACCESS_KEY_ID"
  SECRET_KEY: "$AWS_SECRET_ACCESS_KEY"
  REGION: "AWS_DEFAULT_REGION"
  S3_BUCKET: "$AWS_S3_BUCKET"
  JAR_NAME: "city-api-0.0.1-SNAPSHOT.jar"
  APPLICATION_NAME: "APPLICATION_NAME"

stages:
  - prebuild
  - build

prebuild-job:
  stage: prebuild
  script:
    - echo "Logging into AWS..."
    - echo "Setting AWS Region..."
    - aws configure set region $REGION
    - echo "Setting AWS Access Key Id..."
    - aws configure set aws_acccess_key_id $ACCESS_KEY
    - echo "Setting AWS Setting Access Key..."
    - aws configure set aws_secret_access_key $SECRET_KEY

build-job:
  stage: build
  script:
    - echo "Compiling the code..."
    - "mvn clean compile $MAVEN_CLI_OPTS"
    - echo "Compile complete."
  artifacts:
    paths:
      - target/


