cache:
  paths:
    - ./.m2/repository
  # keep cache across branch
  key: "$CI_PROJECT_PATH"

variables:
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -Dmaven.repo.local=./.m2/repository"

stages:          # List of stages for jobs, and their order of execution
  - build
  - test

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo "Compiling the code..."
    - "mvn clean compile $MAVEN_CLI_OPTS"
    - echo "Compile complete."
  artifacts:
    paths:
      - target/

unittest-job:
  stage: test
  dependencies:
    - build-job
  script:
    - echo "Running unit tests of the City API Application..."
    - "mvn verify $MAVEN_CLI_OPTS"
    - echo "Completed Unit Tests of the City API Application."
  artifacts:
    paths:
      - target/